host:
  'https://kksk.io'

api:
  host: 'https://api.kksk.io'

jwt:
  secret: 'OZ3MbJn98K5CqSR6ZiY27Hvz6uJ13dEQ'

login:
  password:
    cost: 10

cors:
  host: 'https://kksk.io'

slack:
  api_url: 'https://slack.com/api'
  client_id: '9266174033.9265709104'
  client_secret: 'd3edecd5c1ab4dbc6f30c26895f1f553'
  callback_path:
    web: 'https://api.kksk.io/#/callback/slack/success'
    mobile: 'https://api.kksk.io/#/callback/slack/success'
  redirect_path:
    web: 'https://api.kksk.io/#/callback/slack/error'
    mobile: 'https://api.kksk.io/#/callback/slack/error'

applicationinsights:
  instrumentation_key: '45bb61c1-0777-4d55-939f-fd364fb25cbd'

logentries:
  token: 'a2d28004-ce5a-495d-8c2a-60e769d96601'

azure:
  scheduler:
    url: 'https://management.core.windows.net/'
    cloudService: 'CS-JapanWest-scheduler'
    subscriptionId: 'bfa4c371-3b8c-4800-81b9-3b368ccfcaca'
    taskname: 'kksktask'
    sasToken: '?sv=2012-02-12&se=2017-01-19T11%3A07%3A25Z&sp=a&sig=E3lDh16Quz5XOxZ6JS7efA9TZvuqHMX8tWRQ%2F6RTDSY%3D'
    queuename: 'task-dev'
    recurrence:
      frequency: 'minute'
      interval: '10'
