host:
  'http://kksk.io'

api:
  host: 'http://api.kksk.io'

db:
  host: 'kksk.database.windows.net'
  database: 'kksk'
  username: 'kksk'
  password: 'HackM2015'
  dialect: 'mssql'
  pool:
    max: 5
    min: 0
    idel: 10000
  dialectOptions:
    encrypt: true

jwt:
  secret: 'OZ3MbJn98K5CqSR6ZiY27Hvz6uJ13dEQ'

login:
  password:
    cost: 10

slack:
  api_url: 'https://slack.com/api'
  client_id: '2535714809.8192930512'
  client_secret: 'adc1deb59f3f0dc109658223208990d5'
  callback_path: '/callback/slack'
  redirect_path:
    error: '#/callback/slack/error'

applicationinsights:
  instrumentation_key: '45bb61c1-0777-4d55-939f-fd364fb25cbd'

logentries:
  token: 'a2d28004-ce5a-495d-8c2a-60e769d96601'

azure:
  scheduler:
    url: 'https://management.core.windows.net/'
    cloudService: 'CS-JapanWest-scheduler'
    subscriptionId: 'bfa4c371-3b8c-4800-81b9-3b368ccfcaca'
    taskname: 'kksktask'
    sasToken: '?sv=2012-02-12&se=2017-01-19T11%3A07%3A25Z&sp=a&sig=E3lDh16Quz5XOxZ6JS7efA9TZvuqHMX8tWRQ%2F6RTDSY%3D'
