host:
  'http://kksk.io'

api:
  host: 'http://api.kksk.io'

db:
  host: 'kksk.database.windows.net'
  database: 'kksk'
  username: 'kksk'
  password: 'HackM2015'
  dialect: 'mssql'
  pool:
    max: 5
    min: 0
    idel: 10000
  dialectOptions:
    encrypt: true

session:
  secret: 'HackM2015'

login:
  password:
    cost: 10
  redirect_path:
    success: '#/user'

slack:
  client_id: '2535714809.8192930512'
  client_secret: 'adc1deb59f3f0dc109658223208990d5'
  callback_path: '/callback/slack'
  redirect_path:
    success: '#/callback/slack/success'
    error: '#/callback/slack/error'

applicationinsights:
  instrumentation_key: '45bb61c1-0777-4d55-939f-fd364fb25cbd'

logentries:
  token: 'a2d28004-ce5a-495d-8c2a-60e769d96601'
